### PR TITLE
Adding dark mode

### LINKED ISSUE #14: Enhancement: Adding a dark mode
By default, Threema Web has no dark mode/version. If I open Threema Web inside Firefox, where I installed the plugin [Dark Reader](https://addons.mozilla.org/de/firefox/addon/darkreader/), the webpage is converted to a dark version.
Some modifications to the CSS to support a dark mode like this would be nice.

### PR DESCRIPTION
**Pull request by voruti**
Closes #14

Btw: The `nodejs.yml` workflow seems to be broken ...

### CODE REVIEW

**Comment by voruti** [comment]
The missing issues of the "Codacy Static Code Analysis"-check are senseless:
1. "selector-type-no-unknown": Okay, fine, but they are correct. Maybe add them to a list of "known" tags?
2. "no-descending-specificity": These have no influence on the resulting style, but I ordered them like this to keep them in categories (e.g. chat selection, chat history, settings, profile, etc.). Maybe ignore these checks?

What to do now?

**Comment by callFEELD** [comment]
Heya, thank you for your work so far. Appreciate it!

I also partly worked on dark mode (didn't push it). But since some people prefer dark mode and some light mode I would suggest adding an option to switch between both designs.

But I am not sure how the settings options should be integrated tbh.

Maybe you've got an idea.

**Review by callFEELD — CHANGES_REQUESTED** [review]
Quick review point for the CSS:

Could you use [CSS variables](https://www.w3schools.com/css/css3_variables.asp) for the color values. Makes changing the color values easier.

**Comment by voruti** [comment]
I also thought about that and simplest solution would be to adopt the operating system settings (that's how I already implemented it - these CSS rules are only activated if the OS is set to dark mode).

Another idea I had, was to add a new context menu item to the tray icon, which would toggle the dark mode on and off.
This gives rise to some questions: What's the default value? How to save this setting/toggle across app restarts? How to implement this into/with electron? (I never worked with electron before) ...

**Comment by callFEELD** [comment]
> 
> 
> The missing issues of the "Codacy Static Code Analysis"-check are senseless:
> 
>     1. "selector-type-no-unknown": Okay, fine, but they are correct. Maybe add them to a list of "known" tags?
> 
>     2. "no-descending-specificity": These have no influence on the resulting style, but I ordered them like this to keep them in categories (e.g. chat selection, chat history, settings, profile, etc.). Maybe ignore these checks?
> 
> 
> What to do now?

Removed the senseless checks: https://app.codacy.com/gh/callFEELD/Threema-Desktop/pullRequest?prid=7565215

Next commits will probably pass the test.

**Review by callFEELD — APPROVED** [review]
Everything looks good!

**Pull request merged**
